### ISSUE TITLE
encoding problem in license text for gui

### ISSUE THREAD

**Issue by max-attack** [SandiaPSL/UncertaintyCalc#3]
when trying to use the gui with python 3.9 on Windows:

```
>>> from suncal import gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\suncal\gui\__init__.py", line 15, in <module>
    from .gui_main import MainGUI
  File "C:\...\suncal\gui\gui_main.py", line 22, in <module>
    from . import page_about
  File "C:\...\suncal\gui\page_about.py", line 9, in <module>
    from .licenses import licenses
  File "C:\...\suncal\gui\licenses.py", line 14
    IMPLIED WARRANTIES, INCLUDING, BUT<br>NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR<br>A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER<br>OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,<br>EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,<br>PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR<br>PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF<br>LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING<br>NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS<br>SOFTWARE AND DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH<br>DAMAGE.<br>'''

SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte
```

I tried to force utf-8 when the text is written in gen_licenses.py, but it didn't help.  I will send a PR if I get a solution working.

**Comment by max-attack** [comment]
It looks like the encoding issue is in the default licenses.py file that came with the package.  I do not have conda (it is not listed as a dependency) and nothing obviously complained during installation, but gen_licenses.py is not writing the licenses at all because of it.  I made a copy of the default licenses.py, with utf-8 encoding.  I think that should do the trick.  It has worked with py3.9 on Windows 10.  I am going to test on linux and then I will create another PR.
